export const switchTestComponent = (pathname) =>
{
    var TestComponent ;
    console.log("pathname", pathname)
    switch(pathname)
    {
        case "/FarRegion" :
            TestComponent = require('./Backend/ExcelImport/FarRegion/Index.vue').default; break;
        case "/FlowChart" :
            TestComponent = require("./Backend/FlowChart/FlowChart.vue").default;break;
        case "/EQMCarbonEmission" :
            TestComponent = require('./EQM/CarbonEmission/CE_List').default;break;
        case "/EQMEcologicalCheck" :
            TestComponent = require('./EQM/EcologicalCheck/EC_List_V2.vue').default;break;
        case "/QCPlaneWeaknessList" :
            TestComponent = require('./EngSupervise/QCPlaneWeakness/QCPlaneWeaknessList.vue').default;break;
        case "/EAD/CarbonEmission" :
            TestComponent = require('./EngAD/CarbonEmission/CarbonEmission.vue').default;break;
        case "/UserManager" :
            TestComponent = require("./Backend/UserManager/Index.vue").default ;break; 
        case "/RiskManagement/lookup" :
            TestComponent = require('./Backend/RiskManagement/Index.vue').default;break;
        case "/RiskManagement/destruct" :
            TestComponent = require('./Backend/RiskManagement/Index.vue').default;break;
        case "/SignManagement/lookup" :
            TestComponent = require("./Backend/SignManagement/Index.vue").default;break;
        case "/QueryArea/ToolPackage" :
            TestComponent = require("./QueryArea/ToolPackage.vue").default;break;
        case "/QueryArea/ConstCheckOwnerSetting" :
            TestComponent = require("./QueryArea/ConstCheckOwnerSetting.vue").default;break;
        case "/EngRiskFront" :
            TestComponent = require("./EngRiskFront/EngRiskFront.vue").default;break;
        case "/Test" :
            TestComponent = require("./Test.vue").default;break;
        case "/MMPlanTp" :
            TestComponent = require("./Backend/MMPlan/MMPlan.vue").default;break;
        case "/EPC/ConstructionCarbonReduction" :
            TestComponent = require("./EPC/ProgressManage/Construction_CarbonReduction_Main.vue").default;break;
        case "/CarbonReduction" :
            TestComponent = require("./Backend/CarbonReduction/CarbonReduction.vue").default;break;
        case "/TreePlant" :
            TestComponent = require("./Tree/TreeNew").default;break;
        case "/TreePlantList" :
                TestComponent = require("./Tree/TreeList").default;break;
        case "/CarbonEmissionCalXML" :
            TestComponent = require("./QueryArea/CarbonEmissionCalXML/Index.vue").default;break;
        case "/LoginRecord" :
            TestComponent = require("./Backend/LoginRecord/Index.vue").default;break;
        case "/CCTTable" :
            TestComponent = require("./Backend/CarbonEmissionFactor/CCTIndex.vue").default;break;
        case "/CarbonReductionCal" :
            TestComponent = require("./FrontDesk/CarbonReductionCal/Index.vue").default;break;
        case "/pttModal" :
            TestComponent = require("./components/pttModal.vue").default;break;
        case "/UserNotification" :
            TestComponent = require("./Backend/UserNotification/Index.vue").default;break;
        case "/TrainingImage" :
            TestComponent = require("./EngAD/TrainingImage/Index.vue").default;break;
        case "/EADPlaneWeakness" :
            TestComponent = require("./EngAD/PlaneWeakness/PlaneWeaknessAnalysis.vue").default;break;
        case "/SupervisionPlan" :
            TestComponent = require("./FrontDesk/SupervisionPlan/SupervisionPlanEdit.vue").default;break;
        case "/QV_Main" :
            TestComponent = require("./EPC/QualityVerify/QV_Main.vue").default;break;
        case "/EngAnalysisDecision" :
            TestComponent = require("./EngAD/AnalysisDecision.vue").default; break;
        case "/EPCTender/Index3" :
            TestComponent = require("./EPC/Tender/TenderList.vue").default; break;
        case "/EPCTender/Edit" :
            TestComponent = require("./EPC/Tender/TenderEdit.vue").default;break;
        case "/EPCTender/Edit3Plan" :
            TestComponent = require("./EPC/Tender/TenderEdit2_PlanEdit.vue").default;break;
        case "/EPCProgressManage" :
            TestComponent = require('./EPC/ProgressManage/PM_Main.vue').default;break;
        case "/EPCProgressManageChange" :
            TestComponent = require('./EPC/ProgressManage/PM_Main_EngChange.vue').default;break;
        case "/SupervisionPlanEdit" :
            TestComponent = require("./FrontDesk/SupervisionPlan/SupervisionPlanEdit.vue").default;break;
        case "/FlowChartTp" :
            TestComponent = require("./Backend/FlowChart_Test/FlowChart_Test.vue").default;break;
        case "/PortalDepUser" :
            TestComponent = require('./PortalDepUser/PortalDepUser.vue').default;break;
        case "/Backend/TreeListManagement" :
            TestComponent = require('./Backend/TreeListManagement/Index.vue').default;break;
        case "/Backend/ExpertCommittee" :
            TestComponent = require('./Backend/ExpertCommittee/EC_List.vue').default;break;
        case "/Backend/DelEng" :
            TestComponent = require('./Backend/DelEng/DelEng.vue').default;break;
        case "/ESPreWork" :
            TestComponent = require('./EngSupervise/PreWork/PreWorkEngList.vue').default;break;
        case "/ESSuperviseFill" :
            TestComponent = require('./EngSupervise/SuperviseFill/SuperviseFillList.vue').default;break;
        case "/ESSuperviseSta" :
            TestComponent = require('./EngSupervise/SuperviseSta/SuperviseStaList.vue').default;break;
        case "/ESSchedule" :
            TestComponent = require('./EngSupervise/Schedule/ScheduleList.vue').default;break;
        case "/ESSuperviseFill/Edit" :
            TestComponent = require('./EngSupervise/SuperviseFill/SuperviseFillEdit.vue').default;break;
        case "/Backend/RejectCompany" :
            TestComponent = require('./Backend/RejectCompany/RC_List.vue').default;break;
        case "/ERNeedAssessment/Edit" :
            TestComponent = require('./EngReport/NeedAssessment/NeedAssessmentEdit.vue').default;break;
        case "/ERNeedAssessment/Index" :
            TestComponent = require('./EngReport/NeedAssessment/NeedAssessmentList.vue').default;break;
        case "/ERNeedAssessment/EView" :
            TestComponent = require('./EngReport/NeedAssessment/NeedAssessmentView.vue').default;break;
        case "/EADCarbonEmission" :
            TestComponent = require('./EngAD/CarbonEmission/CarbonEmission.vue').default;break;
        case "/AppInstall" :
            TestComponent = require('./FrontDesk/AppInstall/AppInstall.vue').default;break;
        case "/WeakTenderPlanEdit" :
            TestComponent = require('./Backend/WeakTenderPlanEdit/WeakTenderPlanEdit.vue').default;break;
        case "/ERProposalWork/Index" :
            TestComponent = require('./EngReport/ProposalWork/ProposalWorkList.vue').default;break;
        case "/Thsr" :
            TestComponent = require('./Backend/thsr/thsr.vue').default;break;
        case "/TenderPlan/Edit" :
            TestComponent = require('./FrontDesk/TenderPlan/TenderPlanEdit.vue').default;break;   
        case "/TenderPlan/TenderPlanList" :
            TestComponent = require('./FrontDesk/TenderPlan/TenderPlanList.vue').default;break;   
        case "/ESQCPlaneWeakness" :
            TestComponent = require('./EngSupervise/QCPlaneWeakness/QCPlaneWeaknessList.vue').default;break;   
        case "/VendorHireWorkList" :
            TestComponent = require('./Backend/VendorHireWorkList/VendorHireWorkList.vue').default;break;   
        case "/PerformanceScore" :
            TestComponent = require('./Backend/PerformanceScore/PerformanceScore.vue').default;break;  
        case "/ERProposalReview" :
            TestComponent = require('./EngReport/ProposalReview/ProposalReviewList.vue').default;break;  
        case "/ERProposalReview/EView" :
            TestComponent = require('./EngReport/ProposalReview/ProposalReviewView.vue').default;break;  
        case "/ERProposalReview/Edit" :
            TestComponent = require('./EngReport/ProposalReview/ProposalReviewEdit.vue').default;break;  
        case "/ERAnnualFundingReview" :
            TestComponent = require('./EngReport/AnnualFundingReview/AnnualFundingReviewList.vue').default;break;  
        case "/ERApprovedCase" :
            TestComponent = require('./EngReport/ApprovedCase/ApprovedCaseList.vue').default;break;  
        case "/ERProposalWork" :
            TestComponent = require('./EngReport/ProposalWork/ProposalWorkList.vue').default;break;  
        case "/ERApprovedCase/EView" :
            TestComponent = require('./EngReport/ProposalReview/ProposalReviewView.vue').default;break;        
        case "/QualityDeductionPoints" :
            TestComponent = require('./Backend/QualityDeductionPoints/QualityDeductionPoints.vue').default;break;
        case "/AlertSetting" :
        case "/Backend/CEFactor" :
            TestComponent = require('./Backend/CarbonEmissionFactor/CEFactor_Edit.vue').default;break;
        case "/Backend/EngApprovalImport" :
            TestComponent = require('./Backend/EngApprovalImport/EA_List.vue').default;break;
        case "/Menu" :
            TestComponent = require('./Backend/Menu/MenuList.vue').default;break;
        case "/Role" :
            TestComponent = require('./Backend/Role/RoleList.vue').default;break;

        case "/Backend/AlertSetting" :
            TestComponent = require('./Backend/AlertSetting/Index.vue').default;break;

        case "/SystemProblem" :
            TestComponent = require('./SystemProblem/Index.vue').default;break;
        case "/SystemProblemAdmin" :
            TestComponent = require('./SystemProblem/List.vue').default;break;
    }
    console.log("TestComponent", TestComponent)
    return TestComponent; 
}
