//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmmeterRecord
    {
        public int Seq { get; set; }
        public string MachineType { get; set; }
        public string Place { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<decimal> Session1 { get; set; }
        public Nullable<decimal> Session2 { get; set; }
        public Nullable<decimal> Session3 { get; set; }
        public Nullable<decimal> Session4 { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<short> ExecUnitSeq { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<byte> Session { get; set; }
    
        public virtual Unit Unit { get; set; }
    }
}
