//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class APIRecord
    {
        public int Seq { get; set; }
        public int UserMainSeq { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Origin { get; set; }
        public string ErrorCode { get; set; }
        public string ChangeText { get; set; }
        public Nullable<System.DateTime> EndingTime { get; set; }
        public string ActionTable { get; set; }
        public string OriginText { get; set; }
    
        public virtual UserMain UserMain { get; set; }
    }
}
