//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarbonReductionCal
    {
        public int Seq { get; set; }
        public int PC120Num { get; set; }
        public int PC200Num { get; set; }
        public int PC300Num { get; set; }
        public int PC400Num { get; set; }
        public int C15TNum { get; set; }
        public int C21TNum { get; set; }
        public int C35TNum { get; set; }
        public int Num { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public int EngMainSeq { get; set; }
        public Nullable<int> CarbonPayItemSeq { get; set; }
        public Nullable<int> CalType { get; set; }
        public decimal TempResult { get; set; }
    }
}
