//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarbonEmissionFactor
    {
        public int Seq { get; set; }
        public string Code { get; set; }
        public string Item { get; set; }
        public Nullable<decimal> KgCo2e { get; set; }
        public string Unit { get; set; }
        public Nullable<byte> Kind { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUserSeq { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<int> ModifyUserSeq { get; set; }
        public string SubCode { get; set; }
        public string Memo { get; set; }
        public string KeyCode1 { get; set; }
        public string KeyCode2 { get; set; }
        public string KeyCode3 { get; set; }
    }
}
