//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarbonReductionNavvyFactor
    {
        public int Seq { get; set; }
        public string Type1 { get; set; }
        public string Type2 { get; set; }
        public string Description { get; set; }
        public string Unit { get; set; }
        public decimal PC120 { get; set; }
        public decimal PC200 { get; set; }
        public decimal PC300 { get; set; }
        public decimal PC400 { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<int> CreateUserSeq { get; set; }
        public Nullable<int> ModifyUserSeq { get; set; }
    }
}
