//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConstCheckControlSt
    {
        public int Seq { get; set; }
        public Nullable<int> ConstCheckListSeq { get; set; }
        public Nullable<byte> CCFlow1 { get; set; }
        public string CCFlow2 { get; set; }
        public string CCManageItem1 { get; set; }
        public string CCManageItem2 { get; set; }
        public string CCCheckStand1 { get; set; }
        public string CCCheckStand2 { get; set; }
        public string CCCheckTiming { get; set; }
        public string CCCheckMethod { get; set; }
        public string CCCheckFeq { get; set; }
        public string CCIncomp { get; set; }
        public string CCManageRec { get; set; }
        public Nullable<byte> CCType { get; set; }
        public Nullable<bool> CCMemo { get; set; }
        public Nullable<int> CCCheckFields { get; set; }
        public Nullable<int> CCManageFields { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUserSeq { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<int> ModifyUserSeq { get; set; }
        public bool DataKeep { get; set; }
        public byte DataType { get; set; }
    
        public virtual ConstCheckList ConstCheckList { get; set; }
    }
}
