//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConstCheckRec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConstCheckRec()
        {
            this.ConstCheckRecFile = new HashSet<ConstCheckRecFile>();
            this.ConstCheckRecResult = new HashSet<ConstCheckRecResult>();
        }
    
        public int Seq { get; set; }
        public Nullable<int> EngConstructionSeq { get; set; }
        public Nullable<byte> CCRCheckType1 { get; set; }
        public Nullable<int> ItemSeq { get; set; }
        public Nullable<byte> CCRCheckFlow { get; set; }
        public Nullable<System.DateTime> CCRCheckDate { get; set; }
        public Nullable<decimal> CCRPosLati { get; set; }
        public Nullable<decimal> CCRPosLong { get; set; }
        public string CCRPosDesc { get; set; }
        public Nullable<bool> IsManageConfirm { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUserSeq { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<int> ModifyUserSeq { get; set; }
        public Nullable<byte> FormConfirm { get; set; }
        public Nullable<int> SupervisorUserSeq { get; set; }
        public Nullable<int> SupervisorDirectorSeq { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConstCheckRecFile> ConstCheckRecFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConstCheckRecResult> ConstCheckRecResult { get; set; }
        public virtual EngConstruction EngConstruction { get; set; }
    }
}
