//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConstCheckRecResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConstCheckRecResult()
        {
            this.ConstCheckRecResultStandard = new HashSet<ConstCheckRecResultStandard>();
        }
    
        public int Seq { get; set; }
        public Nullable<int> ConstCheckRecSeq { get; set; }
        public Nullable<int> ControllStSeq { get; set; }
        public string CCRRealCheckCond { get; set; }
        public Nullable<byte> CCRCheckResult { get; set; }
        public Nullable<bool> CCRIsNCR { get; set; }
        public byte ResultItem { get; set; }
        public string RecResultRemark { get; set; }
    
        public virtual ConstCheckRec ConstCheckRec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConstCheckRecResultStandard> ConstCheckRecResultStandard { get; set; }
    }
}
