//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EngMain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EngMain()
        {
            this.SchProgressHeader = new HashSet<SchProgressHeader>();
            this.SupDailyDate = new HashSet<SupDailyDate>();
            this.TreePlantMain = new HashSet<TreePlantMain>();
            this.SchEngProgressHeader = new HashSet<SchEngProgressHeader>();
            this.ToolPackage = new HashSet<ToolPackage>();
            this.EngMaterialDeviceList = new HashSet<EngMaterialDeviceList>();
            this.ConstCheckList = new HashSet<ConstCheckList>();
            this.EnvirConsList = new HashSet<EnvirConsList>();
            this.EquOperTestList = new HashSet<EquOperTestList>();
            this.OccuSafeHealthList = new HashSet<OccuSafeHealthList>();
            this.EngConstruction = new HashSet<EngConstruction>();
            this.CarbonEmissionHeader = new HashSet<CarbonEmissionHeader>();
            this.EC_SupDailyDate = new HashSet<EC_SupDailyDate>();
            this.SystemProblem = new HashSet<SystemProblem>();
            this.EngSupervisor = new HashSet<EngSupervisor>();
            this.EC_SchEngProgressHeader = new HashSet<EC_SchEngProgressHeader>();
        }
    
        public int Seq { get; set; }
        public Nullable<short> EngYear { get; set; }
        public string EngNo { get; set; }
        public string EngName { get; set; }
        public string OrganizerUnitCode { get; set; }
        public Nullable<short> OrganizerUnitSeq { get; set; }
        public Nullable<short> ExecUnitSeq { get; set; }
        public string DesignUnitName { get; set; }
        public string DesignManName { get; set; }
        public Nullable<decimal> TotalBudget { get; set; }
        public Nullable<decimal> SubContractingBudget { get; set; }
        public Nullable<decimal> ContractAmountAfterDesignChange { get; set; }
        public Nullable<byte> PurchaseAmount { get; set; }
        public Nullable<byte> ExecType { get; set; }
        public string ProjectScope { get; set; }
        public Nullable<short> EngTownSeq { get; set; }
        public Nullable<int> EngPeriod { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> SchCompDate { get; set; }
        public Nullable<System.DateTime> PostCompDate { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string ApproveNo { get; set; }
        public Nullable<decimal> AwardAmount { get; set; }
        public string BuildContractorName { get; set; }
        public string BuildContractorContact { get; set; }
        public string BuildContractorTaxId { get; set; }
        public string BuildContractorEmail { get; set; }
        public Nullable<bool> IsNeedElecDevice { get; set; }
        public string SupervisorUnitName { get; set; }
        public string SupervisorDirector { get; set; }
        public string SupervisorTechnician { get; set; }
        public string SupervisorTaxid { get; set; }
        public string SupervisorContact { get; set; }
        public string SupervisorSelfPerson1 { get; set; }
        public string SupervisorSelfPerson2 { get; set; }
        public string SupervisorCommPerson1 { get; set; }
        public string SupervisorCommPersion2 { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUserSeq { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<int> ModifyUserSeq { get; set; }
        public Nullable<short> OrganizerSubUnitSeq { get; set; }
        public Nullable<short> ExecSubUnitSeq { get; set; }
        public Nullable<int> OrganizerUserSeq { get; set; }
        public string ConstructionDirector { get; set; }
        public string ConstructionPerson1 { get; set; }
        public string ConstructionPerson2 { get; set; }
        public Nullable<int> PrjXMLSeq { get; set; }
        public Nullable<System.DateTime> AwardDate { get; set; }
        public string DesignUnitEmail { get; set; }
        public string DesignUnitTaxId { get; set; }
        public byte SupervisorExecType { get; set; }
        public string PccesXMLFile { get; set; }
        public Nullable<System.DateTime> PccesXMLDate { get; set; }
        public string SupervisorCommPerson3 { get; set; }
        public Nullable<System.DateTime> SupervisorCommPerson3LicenseExpires { get; set; }
        public Nullable<System.DateTime> SupervisorCommPerson4LicenseExpires { get; set; }
        public Nullable<System.DateTime> EngChangeStartDate { get; set; }
        public Nullable<System.DateTime> WarrantyExpires { get; set; }
        public string SupervisorCommPerson4 { get; set; }
        public Nullable<System.DateTime> EngChangeSchCompDate { get; set; }
        public Nullable<int> CarbonDemandQuantity { get; set; }
        public Nullable<int> ApprovedCarbonQuantity { get; set; }
        public bool OfficialApprovedCarbonQuantity { get; set; }
        public Nullable<int> CarbonDesignQuantity { get; set; }
        public int CarbonTradedQuantity { get; set; }
        public Nullable<int> CarbonConstructionQuantity { get; set; }
        public bool DredgingEng { get; set; }
        public Nullable<System.DateTime> ProgressDoneEarly { get; set; }
    
        public virtual Town Town { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Unit Unit1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchProgressHeader> SchProgressHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupDailyDate> SupDailyDate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreePlantMain> TreePlantMain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchEngProgressHeader> SchEngProgressHeader { get; set; }
        public virtual ConstCheckUser ConstCheckUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolPackage> ToolPackage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EngMaterialDeviceList> EngMaterialDeviceList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConstCheckList> ConstCheckList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnvirConsList> EnvirConsList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquOperTestList> EquOperTestList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OccuSafeHealthList> OccuSafeHealthList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EngConstruction> EngConstruction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarbonEmissionHeader> CarbonEmissionHeader { get; set; }
        public virtual PrjXML PrjXML { get; set; }
        public virtual CarbonReductionCalResult CarbonReductionCalResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EC_SupDailyDate> EC_SupDailyDate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemProblem> SystemProblem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EngSupervisor> EngSupervisor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EC_SchEngProgressHeader> EC_SchEngProgressHeader { get; set; }
    }
}
