//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EngMaterialDeviceTestSummary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EngMaterialDeviceTestSummary()
        {
            this.EngMaterialDeviceTestSummary1 = new HashSet<EngMaterialDeviceTestSummary>();
        }
    
        public int Seq { get; set; }
        public Nullable<int> EngMaterialDeviceListSeq { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public string ItemNo { get; set; }
        public string MDName { get; set; }
        public Nullable<System.DateTime> SchTestDate { get; set; }
        public Nullable<System.DateTime> RealTestDate { get; set; }
        public Nullable<decimal> TestQty { get; set; }
        public Nullable<System.DateTime> SampleDate { get; set; }
        public Nullable<decimal> SampleQty { get; set; }
        public string SampleFeq { get; set; }
        public Nullable<decimal> AccTestQty { get; set; }
        public Nullable<decimal> AccSampleQty { get; set; }
        public Nullable<byte> TestResult { get; set; }
        public string Coworkers { get; set; }
        public string ArchiveNo { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUserSeq { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<int> ModifyUserSeq { get; set; }
        public byte ItemType { get; set; }
        public Nullable<int> RefSeq { get; set; }
    
        public virtual EngMaterialDeviceList EngMaterialDeviceList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EngMaterialDeviceTestSummary> EngMaterialDeviceTestSummary1 { get; set; }
        public virtual EngMaterialDeviceTestSummary EngMaterialDeviceTestSummary2 { get; set; }
    }
}
