//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EngMaterialDeviceList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EngMaterialDeviceList()
        {
            this.EngMaterialDeviceList1 = new HashSet<EngMaterialDeviceList>();
            this.EngMaterialDeviceSummary = new HashSet<EngMaterialDeviceSummary>();
            this.EngMaterialDeviceTestSummary = new HashSet<EngMaterialDeviceTestSummary>();
        }
    
        public int Seq { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public Nullable<int> EngMainSeq { get; set; }
        public Nullable<int> ParentSeq { get; set; }
        public string ItemNo { get; set; }
        public string MDName { get; set; }
        public string ExcelNo { get; set; }
        public string FlowCharOriginFileName { get; set; }
        public string FlowCharUniqueFileName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUserSeq { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<int> ModifyUserSeq { get; set; }
        public bool DataKeep { get; set; }
        public byte DataType { get; set; }
        public Nullable<bool> IsAuditVendor { get; set; }
        public Nullable<bool> IsAuditCatalog { get; set; }
        public Nullable<bool> IsAuditReport { get; set; }
        public Nullable<bool> IsAuditSample { get; set; }
        public string OtherAudit { get; set; }
    
        public virtual EngMain EngMain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EngMaterialDeviceList> EngMaterialDeviceList1 { get; set; }
        public virtual EngMaterialDeviceList EngMaterialDeviceList2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EngMaterialDeviceSummary> EngMaterialDeviceSummary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EngMaterialDeviceTestSummary> EngMaterialDeviceTestSummary { get; set; }
    }
}
