//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EngRiskFrontSubProjectDetailTp
    {
        public int Seq { get; set; }
        public Nullable<int> SubProjectSeq { get; set; }
        public int ParentSeq { get; set; }
        public string StepNo { get; set; }
        public string StepName { get; set; }
        public int HazardTypeSeq { get; set; }
        public string PossibleRiskSituation { get; set; }
        public int Possibility { get; set; }
        public int Severity { get; set; }
        public short IsAcceptable { get; set; }
        public string RisksAndOpportunitiesMeasure { get; set; }
        public Nullable<short> PrincipalSeq { get; set; }
        public string SummaryOfExecutiveResults { get; set; }
        public short IsEffect { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<int> ModifyUser { get; set; }
        public int Level { get; set; }
    
        public virtual EngRiskFrontHazardType EngRiskFrontHazardType { get; set; }
        public virtual EngRiskFrontSubProjectListTp EngRiskFrontSubProjectListTp { get; set; }
    }
}
