//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EngRiskFrontSubProjectList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EngRiskFrontSubProjectList()
        {
            this.EngRiskFrontSubProjectDetail = new HashSet<EngRiskFrontSubProjectDetail>();
        }
    
        public int Seq { get; set; }
        public Nullable<int> EngRiskFrontSeq { get; set; }
        public string ExcelNo { get; set; }
        public string SubProjectName { get; set; }
        public string SubProjectJson { get; set; }
        public string SubProjectFile { get; set; }
        public string ExistingProtectiveFacilities { get; set; }
        public string Equipment { get; set; }
        public string EngControl { get; set; }
        public string ManagementControl { get; set; }
        public string PersonalProtectiveEquipment { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public int CreateUserSeq { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<int> ModifyUserSeq { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EngRiskFrontSubProjectDetail> EngRiskFrontSubProjectDetail { get; set; }
    }
}
