//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquOperControlSt
    {
        public int Seq { get; set; }
        public Nullable<int> EquOperTestStSeq { get; set; }
        public string EPCheckItem1 { get; set; }
        public string EPCheckItem2 { get; set; }
        public string EPStand1 { get; set; }
        public string EPStand2 { get; set; }
        public string EPStand3 { get; set; }
        public string EPStand4 { get; set; }
        public string EPStand5 { get; set; }
        public string EPCheckTiming { get; set; }
        public string EPCheckMethod { get; set; }
        public string EPCheckFeq { get; set; }
        public string EPIncomp { get; set; }
        public string EPManageRec { get; set; }
        public Nullable<byte> EPType { get; set; }
        public Nullable<bool> EPMemo { get; set; }
        public Nullable<int> EPCheckFields { get; set; }
        public Nullable<int> EPManageFields { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUserSeq { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<int> ModifyUserSeq { get; set; }
        public bool DataKeep { get; set; }
        public byte DataType { get; set; }
    
        public virtual EquOperTestList EquOperTestList { get; set; }
    }
}
