//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpertCommittee
    {
        public int Seq { get; set; }
        public string ECName { get; set; }
        public Nullable<System.DateTime> ECBirthday { get; set; }
        public string ECId { get; set; }
        public Nullable<byte> ECKind { get; set; }
        public string ECPosition { get; set; }
        public string ECUnit { get; set; }
        public string ECEmail { get; set; }
        public string ECTel { get; set; }
        public string ECMobile { get; set; }
        public string ECFax { get; set; }
        public string ECAddr1 { get; set; }
        public string ECAddr2 { get; set; }
        public string ECMainSkill { get; set; }
        public string ECSecSkill { get; set; }
        public string ECBankNo { get; set; }
        public Nullable<byte> ECDiet { get; set; }
        public string ECNeed { get; set; }
        public string ECMemo { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<int> ModifyUser { get; set; }
    }
}
