//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InteliAgencyMessage
    {
        public int Seq { get; set; }
        public Nullable<int> Origin { get; set; }
        public string Text { get; set; }
        public System.DateTime CreateTIme { get; set; }
        public Nullable<int> UserMainSeq { get; set; }
        public int AgreeLevel { get; set; }
        public string Suggestion { get; set; }
    }
}
