//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.EDMXModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EQC_NEW_Entities2 : DbContext
    {
        public EQC_NEW_Entities2()
            : base("name=EQC_NEW_Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarbonReductionFactor> CarbonReductionFactor { get; set; }
        public virtual DbSet<CarbonReductionNavvyFactor> CarbonReductionNavvyFactor { get; set; }
        public virtual DbSet<CarbonReductionTruckFactor> CarbonReductionTruckFactor { get; set; }
    }
}
