//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageDownloadAction
    {
        public int Seq { get; set; }
        public string Name { get; set; }
        public Nullable<int> MenuSeq { get; set; }
        public string Url { get; set; }
        public string WhereClasue { get; set; }
        public string RelatedTable { get; set; }
        public string RelatedInjection { get; set; }
        public string MainInjection { get; set; }
        public string StaticInjection { get; set; }
        public string GroupName { get; set; }
        public string FileTableLinkFromEng { get; set; }
        public string FileTableCodition { get; set; }
        public string FileTable { get; set; }
        public string FileTableKey { get; set; }
    
        public virtual Menu Menu { get; set; }
    }
}
