//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformanceScore
    {
        public int Seq { get; set; }
        public Nullable<int> PrjXMLSeq { get; set; }
        public Nullable<decimal> PSTotalScore { get; set; }
        public string PSIssueDate { get; set; }
        public string PSIssueNo { get; set; }
        public Nullable<decimal> PSCompleteAhead { get; set; }
        public Nullable<decimal> PSOverdueCompletion { get; set; }
        public Nullable<decimal> PSAlterPlan { get; set; }
        public Nullable<decimal> PSLiquidDamageAmount { get; set; }
        public Nullable<decimal> PSAcceptanceBonus { get; set; }
        public Nullable<decimal> PSAcceptanceMinus { get; set; }
        public Nullable<decimal> PSConstWork { get; set; }
        public Nullable<decimal> PSAuditBonus { get; set; }
        public Nullable<decimal> PSAuditMinus { get; set; }
        public Nullable<decimal> PSFullTimeEngineerBonus { get; set; }
        public Nullable<decimal> PSFullTimeEngineerMinus { get; set; }
        public Nullable<decimal> PSTechnicianBonus { get; set; }
        public Nullable<decimal> PSQualityAwardBonus { get; set; }
        public Nullable<decimal> PSLaborSafetyAwardBonus { get; set; }
        public Nullable<decimal> PSNoneOccupDisaBonus { get; set; }
        public Nullable<decimal> PSOccupDisaMinus { get; set; }
        public Nullable<decimal> PSEnvirProtectBonus { get; set; }
        public Nullable<decimal> PSPublicBulletinBonus { get; set; }
        public Nullable<decimal> PSSuspensionMinus { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUserSeq { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<int> ModifyUserSeq { get; set; }
    
        public virtual PrjXML PrjXML { get; set; }
    }
}
