//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrjXMLExt
    {
        public int PrjXMLSeq { get; set; }
        public string TenderNo { get; set; }
        public string ExecUnitCd { get; set; }
        public string ExecUnitName { get; set; }
        public string TenderName { get; set; }
        public string SchePerformDesignDate { get; set; }
        public string ActualPerformDesignDate { get; set; }
        public string ScheAnnoDate { get; set; }
        public Nullable<decimal> YearBudget { get; set; }
        public string BidAwardDiff { get; set; }
        public Nullable<decimal> DesignChangeContractAmount { get; set; }
        public Nullable<decimal> CentralPercent { get; set; }
        public Nullable<decimal> LocalPercent { get; set; }
        public Nullable<decimal> FolkPercent { get; set; }
        public string PrjManageUnit { get; set; }
        public string WinningBidder { get; set; }
        public string ContractPercent { get; set; }
        public string TenderType { get; set; }
        public Nullable<decimal> CementMortar { get; set; }
        public Nullable<decimal> MachineMixConcrete { get; set; }
        public Nullable<decimal> ReadyMixedConcrete { get; set; }
        public Nullable<decimal> AsphaltConcrete { get; set; }
        public Nullable<decimal> Sand { get; set; }
        public Nullable<decimal> Gradation { get; set; }
        public Nullable<decimal> CLSM { get; set; }
        public Nullable<decimal> EarthWork { get; set; }
        public Nullable<decimal> ACReduce { get; set; }
        public Nullable<decimal> BottomAsh { get; set; }
        public Nullable<decimal> EAF { get; set; }
        public Nullable<decimal> BOF { get; set; }
        public Nullable<decimal> Rebar { get; set; }
        public Nullable<decimal> SteelPlateSection { get; set; }
        public Nullable<decimal> Template { get; set; }
        public Nullable<decimal> ACReduceOutput { get; set; }
        public Nullable<decimal> EarthWorkOutput { get; set; }
        public string PunishmentMechanism { get; set; }
        public string InceptionDate { get; set; }
        public string SubscriptionDate { get; set; }
        public string PolicyNo { get; set; }
        public string InsuranceStatus { get; set; }
        public string AirPollutionNo { get; set; }
        public string EcologicalCheck { get; set; }
        public string BuildingLicenseNo { get; set; }
        public string BuildingLicenseDate { get; set; }
        public string ScheChangeCloseDate { get; set; }
        public string ProgressMonth { get; set; }
        public Nullable<int> AccuDay { get; set; }
        public Nullable<decimal> ScheProgress { get; set; }
        public Nullable<decimal> ActualProgress { get; set; }
        public Nullable<decimal> DiffProgress { get; set; }
        public string Status { get; set; }
        public string LatePaymentReason { get; set; }
        public string ScheExecMemo { get; set; }
        public string TerminationReason { get; set; }
        public string ImproveDeadline { get; set; }
        public string ActualCompletionDate { get; set; }
        public string ActualAacceptanceCompletionDate { get; set; }
        public Nullable<decimal> AcceptanceDeduction { get; set; }
        public Nullable<decimal> SettlementAmount { get; set; }
        public string ScheSettlementDate { get; set; }
        public string ActualSettlementDate { get; set; }
        public Nullable<decimal> FinalSettlementAmount { get; set; }
        public string AuditDate { get; set; }
        public string Score { get; set; }
        public string PrjItem { get; set; }
        public string BelongPrj { get; set; }
        public string ReportContDate { get; set; }
        public string ReportProgDate { get; set; }
        public string IsRefPerformance { get; set; }
        public Nullable<int> PeopleSupCnt { get; set; }
        public Nullable<System.DateTime> PeopleSupDate { get; set; }
        public Nullable<int> ForeignConstrWorkerNum { get; set; }
        public string LackWorkerCountDate { get; set; }
        public Nullable<int> LackFieldEngineer { get; set; }
        public Nullable<int> LackRebarWorker { get; set; }
        public Nullable<int> LackTemplateWorker { get; set; }
        public Nullable<int> LackCementWorker { get; set; }
        public Nullable<int> LackGeneralWorker { get; set; }
        public Nullable<int> LackMechanicalOperator { get; set; }
        public Nullable<int> LackManualLabor { get; set; }
        public Nullable<int> LackArchitecturalJoinery { get; set; }
        public Nullable<int> LackPlumber { get; set; }
        public Nullable<int> LackConcretePourer { get; set; }
        public Nullable<int> LackPavementWorker { get; set; }
        public Nullable<int> LackMasonry { get; set; }
        public Nullable<int> LackOtherWork { get; set; }
        public string NeedWorkerCountDate { get; set; }
        public Nullable<int> NeedFieldEngineer { get; set; }
        public Nullable<int> NeedRebarWorker { get; set; }
        public Nullable<int> NeedTemplateWorker { get; set; }
        public Nullable<int> NeedCementWorker { get; set; }
        public Nullable<int> NeedGeneralWorker { get; set; }
        public Nullable<int> NeedMechanicalOperator { get; set; }
        public Nullable<int> NeedManualLabor { get; set; }
        public Nullable<int> NeedArchitecturalJoinery { get; set; }
        public Nullable<int> NeedPlumber { get; set; }
        public Nullable<int> NeedConcretePourer { get; set; }
        public Nullable<int> NeedPavementWorker { get; set; }
        public Nullable<int> NeedMasonry { get; set; }
        public Nullable<int> NeedOtherWork { get; set; }
        public string ExistWorkerCountDate { get; set; }
        public Nullable<int> ExistFieldEngineer { get; set; }
        public Nullable<int> ExistRebarWorker { get; set; }
        public Nullable<int> ExistTemplateWorker { get; set; }
        public Nullable<int> ExistCementWorker { get; set; }
        public Nullable<int> ExistGeneralWorker { get; set; }
        public Nullable<int> ExistMechanicalOperator { get; set; }
        public Nullable<int> ExistManualLabor { get; set; }
        public Nullable<int> ExistArchitecturalJoinery { get; set; }
        public Nullable<int> ExistPlumber { get; set; }
        public Nullable<int> ExistConcretePourer { get; set; }
        public Nullable<int> ExistPavementWorker { get; set; }
        public Nullable<int> ExistMasonry { get; set; }
        public Nullable<int> ExistOtherWork { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUserSeq { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<int> ModifyUserSeq { get; set; }
    
        public virtual PrjXML PrjXML { get; set; }
    }
}
