//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgressData
    {
        public int Seq { get; set; }
        public Nullable<int> PrjXMLSeq { get; set; }
        public Nullable<int> PDYear { get; set; }
        public Nullable<int> PDMonth { get; set; }
        public Nullable<decimal> PDAccuScheProgress { get; set; }
        public Nullable<decimal> PDAccuActualProgress { get; set; }
        public Nullable<decimal> PDAccuScheCloseAmount { get; set; }
        public Nullable<decimal> PDAccuActualCloseAmount { get; set; }
        public Nullable<decimal> PDYearAccuScheProgress { get; set; }
        public Nullable<decimal> PDYearAccuActualProgress { get; set; }
        public Nullable<decimal> PDYearAccuScheCloseAmount { get; set; }
        public Nullable<decimal> PDYearAccuActualCloseAmount { get; set; }
        public Nullable<decimal> PDAccuEstValueAmount { get; set; }
        public Nullable<int> PDEstValueRetentAmount { get; set; }
        public string PDExecState { get; set; }
        public string PDActualExecMemo { get; set; }
        public Nullable<decimal> PDAccountPayable { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUserSeq { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<int> ModifyUserSeq { get; set; }
        public Nullable<int> AccuDay { get; set; }
        public string LatePaymentReason { get; set; }
        public string ScheExecMemo { get; set; }
        public string TerminationReason { get; set; }
        public Nullable<int> SupervisionTimes { get; set; }
        public Nullable<decimal> DiffProgress { get; set; }
    
        public virtual PrjXML PrjXML { get; set; }
    }
}
