//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicWorkFirmResume
    {
        public int Seq { get; set; }
        public string CorporationName { get; set; }
        public int GrdAPlusAuditCnt200million5Yrs { get; set; }
        public int GrdAAuditCnt200million5Yrs { get; set; }
        public int GrdBAuditCnt200million5Yrs { get; set; }
        public int GrdCAuditCnt200million5Yrs { get; set; }
        public int GrdAPlusAuditCnt50To200million5Yrs { get; set; }
        public int GrdAAuditCnt50To200million5Yrs { get; set; }
        public int GrdBAuditCnt50To200million5Yrs { get; set; }
        public int GrdCAuditCnt50To200million5Yrs { get; set; }
        public int GrdAPlusAuditCnt10To50million5Yrs { get; set; }
        public int GrdAAuditCnt10To50million5Yrs { get; set; }
        public int GrdBAuditCnt10To50million5Yrs { get; set; }
        public int GrdCAuditCnt10To50million5Yrs { get; set; }
        public int GrdAPlusAuditCnt1To10million5Yrs { get; set; }
        public int GrdAAuditCnt1To10million5Yrs { get; set; }
        public int GrdBAuditCnt1To10million5Yrs { get; set; }
        public int GrdCAuditCnt1To10million5Yrs { get; set; }
        public string ListDate { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUserSeq { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<int> ModifyUserSeq { get; set; }
        public decimal GrdAAuditRatio { get; set; }
        public int GrdCAuditNum { get; set; }
    }
}
