//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchProgressPayItem
    {
        public int Seq { get; set; }
        public Nullable<int> SchProgressHeaderSeq { get; set; }
        public Nullable<System.DateTime> SPDate { get; set; }
        public string PayItem { get; set; }
        public string Description { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string ItemKey { get; set; }
        public string ItemNo { get; set; }
        public string RefItemCode { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUserSeq { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<int> ModifyUserSeq { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public decimal SchProgress { get; set; }
        public decimal DayProgress { get; set; }
        public decimal DayProgressAfter { get; set; }
        public Nullable<int> Days { get; set; }
        public int SchEngProgressPayItemSeq { get; set; }
    
        public virtual SchProgressHeader SchProgressHeader { get; set; }
        public virtual SchEngProgressPayItem SchEngProgressPayItem { get; set; }
    }
}
