//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupDailyDate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupDailyDate()
        {
            this.SupPlanOverview = new HashSet<SupPlanOverview>();
            this.SupDailyReportConstructionEquipment = new HashSet<SupDailyReportConstructionEquipment>();
            this.SupDailyReportConstructionMaterial = new HashSet<SupDailyReportConstructionMaterial>();
            this.SupDailyReportConstructionPerson = new HashSet<SupDailyReportConstructionPerson>();
        }
    
        public int Seq { get; set; }
        public Nullable<int> EngMainSeq { get; set; }
        public System.DateTime ItemDate { get; set; }
        public byte DataType { get; set; }
        public int ItemState { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUserSeq { get; set; }
        public string Weather1 { get; set; }
        public string Weather2 { get; set; }
        public Nullable<System.DateTime> FillinDate { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<int> ModifyUserSeq { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupPlanOverview> SupPlanOverview { get; set; }
        public virtual EngMain EngMain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupDailyReportConstructionEquipment> SupDailyReportConstructionEquipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupDailyReportConstructionMaterial> SupDailyReportConstructionMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupDailyReportConstructionPerson> SupDailyReportConstructionPerson { get; set; }
    }
}
