//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuperviseEng
    {
        public int Seq { get; set; }
        public byte W1 { get; set; }
        public byte W2 { get; set; }
        public byte W3 { get; set; }
        public byte W4 { get; set; }
        public byte W5 { get; set; }
        public byte W6 { get; set; }
        public byte W7 { get; set; }
        public byte W8 { get; set; }
        public byte W9 { get; set; }
        public byte W10 { get; set; }
        public byte W11 { get; set; }
        public byte W12 { get; set; }
        public byte W13 { get; set; }
        public byte W14 { get; set; }
        public Nullable<System.DateTime> SuperviseDate { get; set; }
        public Nullable<int> LeaderSeq { get; set; }
        public string Memo { get; set; }
        public string BriefingPlace { get; set; }
        public string BriefingAddr { get; set; }
        public Nullable<bool> IsVehicleDisp { get; set; }
        public Nullable<bool> IsTHSR { get; set; }
        public string AdminContact { get; set; }
        public string AdminTel { get; set; }
        public string AdminMobile { get; set; }
        public string RiverBureauContact { get; set; }
        public string RiverBureauTel { get; set; }
        public string RiverBureauMobile { get; set; }
        public string LocalGovContact { get; set; }
        public string LocalGovTel { get; set; }
        public string LocalGovMobile { get; set; }
        public Nullable<int> ToBriefingDrive { get; set; }
        public Nullable<System.TimeSpan> SuperviseStartTime { get; set; }
        public Nullable<byte> SuperviseOrder { get; set; }
        public Nullable<bool> IsConfirm { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<int> ModifyUser { get; set; }
        public Nullable<int> SupervisePhaseSeq { get; set; }
        public Nullable<byte> SuperviseMode { get; set; }
        public Nullable<int> PrjXMLSeq { get; set; }
        public Nullable<int> CommitteeAverageScore { get; set; }
        public string Inspect { get; set; }
        public Nullable<System.DateTime> SuperviseEndDate { get; set; }
        public Nullable<decimal> LeaderScore { get; set; }
    
        public virtual PrjXML PrjXML { get; set; }
        public virtual UserMain UserMain { get; set; }
    }
}
