//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemProblem
    {
        public int Seq { get; set; }
        public Nullable<int> ProblemTypeSeq { get; set; }
        public Nullable<int> EngSeq { get; set; }
        public Nullable<int> MenuSeq { get; set; }
        public string Title { get; set; }
        public string Descriptoin { get; set; }
        public Nullable<int> UserMainSeq { get; set; }
        public string Anwser { get; set; }
        public Nullable<System.DateTime> CreateTIme { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<bool> AdminCheck { get; set; }
    
        public virtual EngMain EngMain { get; set; }
        public virtual Menu Menu { get; set; }
        public virtual SystemProblemType SystemProblemType { get; set; }
        public virtual UserMain UserMain { get; set; }
    }
}
