//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreePlantMain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TreePlantMain()
        {
            this.TreePlantMonth = new HashSet<TreePlantMonth>();
            this.TreePlantNumList = new HashSet<TreePlantNumList>();
        }
    
        public int Seq { get; set; }
        public Nullable<int> EngCreatType { get; set; }
        public Nullable<int> EngSeq { get; set; }
        public Nullable<int> TPEngTypeSeq { get; set; }
        public string EngName { get; set; }
        public Nullable<short> EngTownSeq { get; set; }
        public Nullable<short> OrganizerUnitSeq { get; set; }
        public Nullable<short> ExecUnitSeq { get; set; }
        public Nullable<short> ExecSubUnitSeq { get; set; }
        public Nullable<int> OrganizerUserSeq { get; set; }
        public Nullable<decimal> UncontractedFunds { get; set; }
        public Nullable<int> TreePlantTypeSeq { get; set; }
        public Nullable<System.DateTime> ScheduledPlantDate { get; set; }
        public Nullable<System.DateTime> ScheduledCompletionDate { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public Nullable<decimal> ScheduledPlantTotalArea { get; set; }
        public Nullable<System.DateTime> ActualCompletionPlantDate { get; set; }
        public string Contractor { get; set; }
        public string ContractorUniformNumber { get; set; }
        public string PlantContractor { get; set; }
        public string PlantContractorUniformNumber { get; set; }
        public Nullable<decimal> ContractExpenses { get; set; }
        public Nullable<decimal> PlantExpenses { get; set; }
        public string ExecutionStatusDescription { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public int CreateUserSeq { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<int> ModifyUserSeq { get; set; }
        public string EngNo { get; set; }
        public Nullable<int> EngYear { get; set; }
        public Nullable<int> CitySeq { get; set; }
        public string PlaceNumber { get; set; }
    
        public virtual EngMain EngMain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreePlantMonth> TreePlantMonth { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreePlantNumList> TreePlantNumList { get; set; }
    }
}
