//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_EngReportApprove
    {
        public int Seq { get; set; }
        public Nullable<int> EngReportSeq { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> ApprovalModuleListSeq { get; set; }
        public Nullable<short> UnitSeq { get; set; }
        public Nullable<short> SubUnitSeq { get; set; }
        public Nullable<short> PositionSeq { get; set; }
        public Nullable<int> UserMainSeq { get; set; }
        public Nullable<System.DateTime> ApproveTime { get; set; }
        public Nullable<int> ApproveUserSeq { get; set; }
        public string ApproveUser { get; set; }
        public string Signature { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUserSeq { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<int> ModifyUserSeq { get; set; }
        public string FormCode { get; set; }
        public string FormName { get; set; }
        public Nullable<int> ApprovalWorkFlow { get; set; }
        public Nullable<int> Approver { get; set; }
        public string ApproverName { get; set; }
        public Nullable<int> ApprovingUnitSeq { get; set; }
        public string ApprovingUnitName { get; set; }
        public Nullable<int> ApprovalMethod { get; set; }
        public string ApprovalMethodName { get; set; }
        public Nullable<int> EmailNotification { get; set; }
        public string EmailNotificationName { get; set; }
    }
}
