//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_EngReportList
    {
        public int Seq { get; set; }
        public Nullable<short> RptYear { get; set; }
        public string RptName { get; set; }
        public Nullable<int> RptTypeSeq { get; set; }
        public string EngState { get; set; }
        public Nullable<short> ExecUnitSeq { get; set; }
        public Nullable<short> ExecSubUnitSeq { get; set; }
        public string OriginAndScope { get; set; }
        public Nullable<int> OriginAndScopeUserSeq { get; set; }
        public string OriginAndScopeUserName { get; set; }
        public Nullable<System.DateTime> OriginAndScopeUpdateTime { get; set; }
        public Nullable<bool> OriginAndScopeReviewState { get; set; }
        public Nullable<int> OriginAndScopeAssignReviewUserSeq { get; set; }
        public string OriginAndScopeAssignReviewUserName { get; set; }
        public Nullable<int> OriginAndScopeUpdateReviewUserSeq { get; set; }
        public string OriginAndScopeUpdateReviewUserName { get; set; }
        public Nullable<System.DateTime> OriginAndScopeReviewTime { get; set; }
        public string RelatedReportResults { get; set; }
        public Nullable<int> RelatedReportResultsUserSeq { get; set; }
        public string RelatedReportResultsUserName { get; set; }
        public Nullable<System.DateTime> RelatedReportResultsUpdateTime { get; set; }
        public Nullable<bool> RelatedReportResultsReviewState { get; set; }
        public Nullable<int> RelatedReportResultsAssignReviewUserSeq { get; set; }
        public string RelatedReportResultsAssignReviewUserName { get; set; }
        public Nullable<int> RelatedReportResultsUpdateReviewUserSeq { get; set; }
        public string RelatedReportResultsUpdateReviewUserName { get; set; }
        public Nullable<System.DateTime> RelatedReportResultsReviewTime { get; set; }
        public string FacilityManagement { get; set; }
        public Nullable<int> FacilityManagementUserSeq { get; set; }
        public string FacilityManagementUserName { get; set; }
        public Nullable<System.DateTime> FacilityManagementUpdateTime { get; set; }
        public Nullable<bool> FacilityManagementReviewState { get; set; }
        public Nullable<int> FacilityManagementAssignReviewUserSeq { get; set; }
        public string FacilityManagementAssignReviewUserName { get; set; }
        public Nullable<int> FacilityManagementUpdateReviewUserSeq { get; set; }
        public string FacilityManagementUpdateReviewUserName { get; set; }
        public Nullable<System.DateTime> FacilityManagementReviewTime { get; set; }
        public string ProposalScopeLand { get; set; }
        public Nullable<int> ProposalScopeLandUserSeq { get; set; }
        public string ProposalScopeLandUserName { get; set; }
        public Nullable<System.DateTime> ProposalScopeLandUpdateTime { get; set; }
        public Nullable<bool> ProposalScopeLandReviewState { get; set; }
        public Nullable<int> ProposalScopeLandAssignReviewUserSeq { get; set; }
        public string ProposalScopeLandAssignReviewUserName { get; set; }
        public Nullable<int> ProposalScopeLandUpdateReviewUserSeq { get; set; }
        public string ProposalScopeLandUpdateReviewUserName { get; set; }
        public Nullable<System.DateTime> ProposalScopeLandReviewTime { get; set; }
        public string LocationMap { get; set; }
        public string LocationMapFileName { get; set; }
        public string AerialPhotography { get; set; }
        public string AerialPhotographyFileName { get; set; }
        public string ScenePhoto { get; set; }
        public string ScenePhotoFileName { get; set; }
        public string BaseMap { get; set; }
        public string BaseMapFileName { get; set; }
        public string EngPlaneLayout { get; set; }
        public string EngPlaneLayoutFileName { get; set; }
        public string LongitudinalSection { get; set; }
        public string LongitudinalSectionFileName { get; set; }
        public string StandardSection { get; set; }
        public string StandardSectionFileName { get; set; }
        public Nullable<int> NeedAssessmenApproval { get; set; }
        public string NeedAssessmenApprovalName { get; set; }
        public Nullable<int> EvaluationResult { get; set; }
        public string EvaluationResultName { get; set; }
        public string ER1_1 { get; set; }
        public string ER1_2 { get; set; }
        public string ER2_1 { get; set; }
        public string ER2_2 { get; set; }
        public string ER3 { get; set; }
        public string ER4 { get; set; }
        public string ER6 { get; set; }
        public Nullable<int> ProposalReviewTypeSeq { get; set; }
        public string ProposalReviewTypeName { get; set; }
        public Nullable<int> ProposalReviewAttributesSeq { get; set; }
        public string ProposalReviewAttributesName { get; set; }
        public Nullable<int> RiverSeq { get; set; }
        public short RiverSeq1 { get; set; }
        public short RiverSeq2 { get; set; }
        public short RiverSeq3 { get; set; }
        public string RiverName1 { get; set; }
        public string RiverName2 { get; set; }
        public string RiverName3 { get; set; }
        public Nullable<int> DrainSeq { get; set; }
        public string DrainName { get; set; }
        public string Coastal { get; set; }
        public string LargeSectionChainage { get; set; }
        public Nullable<int> CitySeq { get; set; }
        public string CityName { get; set; }
        public Nullable<int> TownSeq { get; set; }
        public string TownName { get; set; }
        public Nullable<decimal> CoordX { get; set; }
        public Nullable<decimal> CoordY { get; set; }
        public string EngineeringScale { get; set; }
        public string ProcessReason { get; set; }
        public string EngineeringScaleMemo { get; set; }
        public string RelatedReportContent { get; set; }
        public Nullable<int> HistoricalCatastrophe { get; set; }
        public string HistoricalCatastropheName { get; set; }
        public string HistoricalCatastropheMemo { get; set; }
        public string ProtectionTarget { get; set; }
        public string SetConditions { get; set; }
        public string EcologicalConservationD01 { get; set; }
        public string D01FileName { get; set; }
        public string EcologicalConservationD02 { get; set; }
        public string D02FileName { get; set; }
        public string EcologicalConservationD03 { get; set; }
        public string D03FileName { get; set; }
        public string EcologicalConservationD04 { get; set; }
        public string D04FileName { get; set; }
        public string EcologicalConservationD05 { get; set; }
        public string D05FileName { get; set; }
        public string EcologicalConservationD06 { get; set; }
        public string D06FileName { get; set; }
        public Nullable<decimal> DemandCarbonEmissions { get; set; }
        public string DemandCarbonEmissionsMemo { get; set; }
        public Nullable<int> IsProposalReview { get; set; }
        public string IsProposalReviewName { get; set; }
        public Nullable<int> ProposalAuditOpinion { get; set; }
        public string ProposalAuditOpinionName { get; set; }
        public Nullable<int> ReviewSort { get; set; }
        public Nullable<int> ApprovedFund { get; set; }
        public Nullable<decimal> ApprovedCarbonEmissions { get; set; }
        public Nullable<decimal> RefCarbonEmission { get; set; }
        public Nullable<int> Expenditure { get; set; }
        public string Resolution { get; set; }
        public Nullable<int> ResolutionAuditOpinion { get; set; }
        public string ResolutionAuditOpinionName { get; set; }
        public string EngNo { get; set; }
        public Nullable<int> IsTransfer { get; set; }
        public string IsTransferName { get; set; }
        public string ExecUnit { get; set; }
        public string ExecSubUnit { get; set; }
        public string ExecUser { get; set; }
        public decimal CarbonEmissionRatio { get; set; }
        public decimal RegressionCurve { get; set; }
        public decimal PriceAdjustmentIndex { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public int CreateUserSeq { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<int> ModifyUserSeq { get; set; }
        public Nullable<int> EstimatedLandAcquisitionCosts { get; set; }
        public string ManagementPlanningLayoutSituation { get; set; }
        public Nullable<int> IsFloodControlRecords { get; set; }
        public Nullable<int> EstimatedExpenditureCurrentYear { get; set; }
        public Nullable<int> ExpensesSubsequentYears { get; set; }
        public string BookingProcess_SY { get; set; }
        public string BookingProcess_SM { get; set; }
        public string BookingProcess_EY { get; set; }
        public string BookingProcess_EM { get; set; }
        public string Remark { get; set; }
    }
}
