//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewPrjXMLPlaneWeakness
    {
        public int Seq { get; set; }
        public Nullable<int> PrjXMLSeq { get; set; }
        public byte W1 { get; set; }
        public byte W2 { get; set; }
        public byte W3 { get; set; }
        public byte W4 { get; set; }
        public byte W5 { get; set; }
        public byte W6 { get; set; }
        public byte W7 { get; set; }
        public byte W8 { get; set; }
        public byte W9 { get; set; }
        public Nullable<byte> W10 { get; set; }
        public byte W11 { get; set; }
        public byte W12 { get; set; }
        public byte W13 { get; set; }
        public byte W14 { get; set; }
    }
}
