//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourtVerdict
    {
        public int Seq { get; set; }
        public string JID { get; set; }
        public string JYear { get; set; }
        public string JCase { get; set; }
        public string JNo { get; set; }
        public string JDate { get; set; }
        public string JTitle { get; set; }

        public string JFull { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<int> ModifyUser { get; set; }
    }
}
