//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.Models
{
    using EQC.EDMXModel;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EQC_NEWEntities1 : System.Data.Entity.DbContext
    {
        public EQC_NEWEntities1()
            : base("name=EQC_NEWEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country2WRAMapping> Country2WRAMapping { get; set; }
        public virtual DbSet<wraControlPlanNo> wraControlPlanNo { get; set; }
        public virtual DbSet<QualityDeductionPoints> QualityDeductionPoints { get; set; }
        public virtual DbSet<PublicWorkFirmResume> PublicWorkFirmResume { get; set; }
        public virtual DbSet<TechnicalArtical> TechnicalArtical { get; set; }
        public virtual DbSet<TechnicalArticalMTag> TechnicalArticalMTag { get; set; }
        public virtual DbSet<CourtVerdict> CourtVerdict { get; set; }
        public virtual DbSet<THSR> THSR { get; set; }
    }
}
