using System;

namespace EQC.Models
{
    public class PrjXMLModel
    {//標案主檔(從XML匯入)
        public int Seq { get; set; }
        public string TenderNo { get; set; }
        public string ExecUnitCd { get; set; }
        public string ExecUnitName  { get; set; }
        public string TenderName { get; set; }
        public string PrjName { get; set; }
        public string EngType  { get; set; }
        public string TownName { get; set; }
        public decimal? CoordX { get; set; }
        public decimal? CoordY { get; set; }
        public string Location { get; set; }
        public string PlanOrganizerName { get; set; }
        public string PlanNo { get; set; }
        public string CompetentAuthority { get; set; }
        public string OrganizerName { get; set; }
        public string FundingSourceName { get; set; }
        public string TenderNoticeUnit { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public string Weights { get; set; }
        public string EngOverview { get; set; }
        public int? SteelDemand { get; set; }
        public int? ConcreteDemand { get; set; }
        public int? EarchworkDemand { get; set; }
        public string DurationCategory { get; set; }
        public int? TotalDays { get; set; }
        public string DurationDesc { get; set; }
        public string BudgetAccount { get; set; }
        public decimal? TotalEngBudget { get; set; }
        public decimal? OutsourcingBudget { get; set; }
        public int? SupplyMaterialCost { get; set; }
        public int? LandPurCompen { get; set; }
        public decimal? EngManageFee { get; set; }
        public decimal? AirPollutionFee { get; set; }
        public decimal? OtherFee { get; set; }
        public string PlanningUnitName { get; set; }
        public string DesignUnitName  { get; set; }
        public decimal? DesignFee { get; set; }
        public string DesignMemo { get; set; }
        public string SupervisionUnitName { get; set; }
        public decimal? SupervisionFee { get; set; }
        public string SupervisionMemo { get; set; }
        public string ContractorName1 { get; set; }
        public string ContractorName2 { get; set; }
        public string InsuranceDate { get; set; }
        public decimal? InsuranceAmount { get; set; }
        public string InsuranceNo { get; set; }
        public string ActualAnnoDate { get; set; }
        public string ScheBidReviewDate { get; set; }
        public string ActualBidReviewDate { get; set; }
        public string ScheBidOpeningDate { get; set; }
        public string ActualBidOpeningDate { get; set; }
        public string ScheBidAwardDate { get; set; }
        public string ActualBidAwardDate { get; set; }
        public string ScheBiddingMethod { get; set; }
        public string ActualBiddingMethod { get; set; }
        public string BidAwardMethod { get; set; }
        public string ContractFeePayMethod { get; set; }
        public decimal? EstimateBasePrice { get; set; }
        public decimal? RendBasePrice { get; set; }
        public decimal? BidAmount { get; set; }
        public string ContractNo { get; set; }
        public int? Prepayment { get; set; }
        public string ScheStartDate { get; set; }
        public string ActualStartDate { get; set; }
        public string ScheCompletionDate { get; set; }
        public string ScheCompletCloseDate  { get; set; }
        public decimal? QualityControlFee { get; set; }
        public string QualityPlanApproveUnit { get; set; }
        public string QualityPlanApproveDate { get; set; }
        public string QualityPlanApproveNo { get; set; }
        public string SupervisionPlanApproveUnit { get; set; }
        public string SupervisionPlanApproveDate { get; set; }
        public string SupervisionPlanApproveNo { get; set; }
        public string SiteContactMemo { get; set; }
        public bool? IsChangeContract { get; set; }
        public bool? IsAppendAgreement { get; set; }
        public bool? IsForYear97 { get; set; }
        public string ForMade97Month { get; set; }
        public bool? IsAppleBeforeClose { get; set; }
        public int? PriceAdjust { get; set; }
        public int? BudgetAvail { get; set; }
        public DateTime? CreateTime { get; set; }
        public int? CreateUserSeq { get; set; }
        public DateTime? ModifyTime { get; set; }
        public int? ModifyUserSeq { get; set; }
        public Int16? TenderYear { get; set; }
        public string NumOfAnnounce { get; set; }
        public string Chief { get; set; }
        public decimal? PlanningFee { get; set; }
    }
}
