//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.Models
{
    using System;
    using System.Collections.Generic;

    public partial class TechnicalArtical
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TechnicalArtical()
        {
            this.TechnicalArticalMTag = new HashSet<TechnicalArticalMTag>();
        }

        public int Seq { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }



        //public long createTimeStamp {
        //    get{
        //        if (CreateTime == null) return -1;
        //        return (new DateTimeOffset((DateTime)CreateTime)).ToUnixTimeSeconds();
        //    }
        //}
        //public long modifyTimeStamp
        //{
        //    get
        //    {
        //        if (ModifyTime == null) return -1;
        //        return (new DateTimeOffset((DateTime)ModifyTime)).ToUnixTimeSeconds();
        //    }
        //}
        private DateTime? modifyTime;

        private DateTime? createTime;
        public string CreateTimeStr
        {
            get
            {
                return createTime?.ToString("yyyy-MM-dd HH:mm:ss");
            }

        } //(datetime, null)
        public DateTime? CreateTime
        {
            get
            {
                return createTime;
            }

            set
            {
                createTime = value;
            }
        }
        public string ModifyTimeStr
        {
            get
            {
                return modifyTime?.ToString("yyyy-MM-dd HH:mm:ss");
            }

        } //(datetime, null)
        public DateTime? ModifyTime
        {
            get
            {
                return modifyTime;
            }
            set
            {
                modifyTime = value;
            }
        }
        public int Author { get; set; }
        public string Url { get; set; }
        public int Click { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TechnicalArticalMTag> TechnicalArticalMTag { get; set; }
    }
}
