//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THSR
    {
        public int Seq { get; set; }
        public Nullable<byte> Direction { get; set; }
        public string DirectionText
        {
            get
            {
                if (Direction == 1)
                    return "北上";
                if (Direction == 2)
                    return "南下";

                return "";

            }
            set
            {
                switch(value)
                {
                    case "北上": Direction = 1;break;
                    case "南下": Direction = 2; break;
                    default: Direction = 0;break;
                }
            }
        }
        public string CarNo { get; set; }

        private string startStationName;
        public string StartStationName {
            get
            {
                if (startStationName == "全部" ) return "";

                return startStationName;
            }
            set
            {
                startStationName = value;
            }
        }
        
        public string DepartureTime { get; set; }
        public string endingStationName { get; set; }
        public string EndingStationName
    {
            get
            {
                if (endingStationName == "全部" ) return "";

                return endingStationName;
            }
            set
            {
                endingStationName = value;
            }
        }
        public string ArrivalTime { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<int> ModifyUser { get; set; }
    }
}
